# Generated by Django 5.1.7 on 2025-03-30 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('leaves', models.TextField()),
                ('flowers', models.TextField()),
                ('fruits', models.TextField()),
                ('growth', models.TextField()),
                ('uses', models.TextField()),
                ('image_filename', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='plants/')),
            ],
        ),
    ]
